### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by neooriginal** [nikakoy131/node-restream#1]
Hi! Could you explain what i have to put in 
in, out, name?

Thanks!

**Comment by nikakoy131** [comment]
Hello! Yes, of course.
**In** - it is a full RTMP url from where you want to get the stream. In my case, it was my RTMP server (Nginx based)
**out** - full RTMP url of the server where you want to send the stream. In my cases, it was youtube, Facebook, other custom RTMP server
**name** - just the name for your streams list

**Comment by neooriginal** [comment]
Thanks!
